In [1]:
#Lab 3
#Task 1 simple classification on the Iris Dataset
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

In [2]:
iris = datasets.load_iris()
X = iris["data"][:, (2, 3)] # petal length, petal width
y = (iris["target"] == 2).astype(np.float64) # Iris-Virginica

In [3]:
std_scaler = StandardScaler()
X_scaled = std_scaler.fit_transform(X)

In [4]:
svm_clf = LinearSVC(C=1, loss="hinge", random_state=42)
svm_clf.fit(X_scaled, y)

/Applications/anaconda3/lib/python3.11/site-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


LinearSVC(C=1, loss='hinge', random_state=42)

In [5]:
svm_clf.predict(X_scaled[10].reshape(1,-1))

array([0.])

In [6]:
#The -1 is a convenient as it automatically knows the number of columns
#Reshape tool makes this 2-D 

In [7]:
#Task 2 Looking at full dataset and create confusion matrix
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier(random_state = 10)
y_pred = cross_val_predict(sgd_clf, X, y)

In [8]:
cm_iris = confusion_matrix(y, y_pred)

In [9]:
print(cm_iris)
#The classifier performs well but still with some misclassifications.

[[95  5]
 [ 4 46]]


In [10]:
X_full = iris["data"]
y_full = iris["target"]
print(iris.data.shape)

(150, 4)


In [11]:
X_train, X_test, y_train, y_test = X_full[:1400], X_full[1400:], y_full[:1400], y_full[1400:] 
y_train_2 = (y_train == 2)
y_test_2 = (y_test == 2)

svm_clf = LinearSVC(C=1, loss="hinge", random_state=42)
svm_clf.fit(X_train, y_train_2)

/Applications/anaconda3/lib/python3.11/site-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
/Applications/anaconda3/lib/python3.11/site-packages/sklearn/svm/_base.py:1242: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC(C=1, loss='hinge', random_state=42)

In [12]:
#Task 3 Classifying non-linear data using polynomial features
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt
poly_features = PolynomialFeatures(degree=4, include_bias=False)
X_poly = poly_features.fit_transform(X_full)
X_poly_scaled = std_scaler.fit_transform(X_poly)
poly_svm_clf = LinearSVC(C=10, loss="hinge", random_state=42)
poly_svm_clf.fit(X_poly_scaled, y)

/Applications/anaconda3/lib/python3.11/site-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
/Applications/anaconda3/lib/python3.11/site-packages/sklearn/svm/_base.py:1242: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC(C=10, loss='hinge', random_state=42)

In [13]:
from sklearn.svm import SVC
X_scaled = poly_features.fit_transform(X_full)
# Create a classifier with a polynomial kernel of degree 3 and fit this to the data
poly_k_svm_clf = SVC(kernel="poly", degree=7, coef0=1, C=5)
poly_k_svm_clf.fit(X_scaled, y)
y_poly_pred = poly_k_svm_clf.predict(X_scaled)
confusion_matrix(y, y_poly_pred)

array([[98,  2],
       [ 0, 50]])

In [14]:
#Using a Radial Basis Function Kernel (RBF)

In [15]:
rbf_svm_clf = SVC(kernel="rbf", gamma=5, C=0.0001)
rbf_svm_clf.fit(X_scaled, y)
y_rbf_pred = rbf_svm_clf.predict(X_scaled)
confusion_matrix(y, y_rbf_pred)

array([[100,   0],
       [ 50,   0]])

In [23]:
# Task 5 Multi-Class Classification using SVMs 
wine = datasets.load_wine()
Xwin = wine["data"]
ywin = wine["target"]
print(wine.data.shape)

(178, 13)


In [24]:
X_wintrain, X_wintest, y_wintrain, y_wintest = Xwin[:130], Xwin[130:], ywin[:130], ywin[130:] 

In [25]:
from sklearn.svm import SVC
svm_clf = SVC()
svm_clf.fit(X_wintrain, y_wintrain)

SVC()

In [26]:
print("Shape of X_train:", X_wintrain.shape)
print("Shape of X_test:", X_wintest.shape)

Shape of X_train: (130, 13)
Shape of X_test: (48, 13)


In [27]:
y_wine_pred = svm_clf.predict(X_wintest)

In [28]:
from sklearn.multiclass import OneVsRestClassifier
# ovr_svc_clf = OneVsRestClassifier(SVC(kernel="rbf", gamma=5, C=1)) # e.g. does badly
ovr_svc_clf = OneVsRestClassifier(SVC(kernel="poly", degree=7, coef0=1, C=5)) # e.g. does better
ovr_svc_clf.fit(X_wintrain, y_wintrain)
wine_preds = ovr_svc_clf.predict(X_wintest)
confusion_matrix(y_wintest, y_wine_pred)

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [ 5, 43,  0]])