In [1]:
#SVM Regression
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_predict
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt
from sklearn.svm import SVC

In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
boston = pd.read_csv("boston-housing-dataset.csv")

In [12]:
X = boston["data"]
y = boston['target']
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.25, random_state = 42)

KeyError: 'data'

In [10]:
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (506, 14)
Shape of y: (506,)


In [13]:
#Decision Trees
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

iris = load_iris()
X = iris.data[:, 2:]
y = iris.target

tree_clf = DecisionTreeClassifier(max_depth=2)
tree_clf.fit(X, y)

DecisionTreeClassifier(max_depth=2)

In [16]:
wine = datasets.load_wine()
Xwin = wine["data"]
ywin = wine["target"]
X_wintrain, X_wintest, y_wintrain, y_wintest = train_test_split(Xwin, ywin, test_size=0.2, random_state=42)

In [15]:
tree_clf = DecisionTreeClassifier(max_depth=2)
tree_clf.fit(X_wintrain, y_wintrain)

DecisionTreeClassifier(max_depth=2)

In [19]:
y_winpred = tree_clf.predict(X_wintest)

In [21]:
wine_tree_cm = confusion_matrix(y_wintest, y_winpred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[14  0  0]
 [ 0 13  1]
 [ 0  1  7]]


In [25]:
#Final Task Decision Tree Regression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
tree_reg = DecisionTreeRegressor(min_samples_leaf=3) # explore min_samples = e.g. put to 1 to see what happens
tree_reg.fit(X_wintrain,y_wintrain)
wine_train_preds = tree_reg.predict(X_wintrain) # Check fit
lin_mse = mean_squared_error(y_wintrain, wine_train_preds)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

0.0998825601473863

In [29]:
wine_test_pred = tree_reg.predict(X_wintest)
lin_mse = mean_squared_error(y_wintest, wine_test_pred)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

0.3888888888888889